Help:
  - "&a/FAchievements <player> <achievement> &f- &7You need an achievement to send!"
  - "&a/FAchievements reload &f-&a Reload config"
Achievements: "&a%p &ahas just earned the achievement&b %a"
Reload: "&f[&bFAchievements&f]&a Reloaded "